CREATE DATABASE DB_GENESCOLA;
USE DB_GENESCOLA;
CREATE TABLE TB_ALUNOS(ID BIGINT (5) AUTO_INCREMENT,
NOME VARCHAR (255),
SERIE INT,
TURMA VARCHAR (255),
TURNO VARCHAR (255),
MEDIA FLOAT,
PRIMARY KEY(ID));

INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("CAIO",9,"A","MATUTINO",7);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("BIANCA",8,"B","VESPERTINO",8);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("THAIS",5,"C","MATUTINO",8);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("MONICA",6,"A","VESPERTINO",6);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("BENICIO",3,"A","MATUTINO",8);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("ANTONIO",4,"C","MATUTINO",7);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("MIGUEL",5,"A","VESPERTINO",8);
INSERT INTO TB_ALUNOS (NOME,SERIE,TURMA,TURNO,MEDIA)
VALUES("LAURA",9,"B","MATUTINO",9)

SELECT * FROM TB_ALUNOS;

SELECT * FROM TB_ALUNOS WHERE MEDIA > 7.0;
SELECT * FROM TB_ALUNOS WHERE MEDIA < 7.0;

UPDATE TB_ALUNOS SET MEDIA = 8.5 WHERE ID =3;






